// <auto-generated />
using System;
using Gym_Management_System.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gym_Management_System.Migrations
{
    [DbContext(typeof(GymContext))]
    [Migration("20260505060510_AddDataSeeding")]
    partial class AddDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gym_Management_System.Data.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DiscountPercentage = 20m,
                            EndDate = new DateTime(2026, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "New Year Offer",
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 1
                        },
                        new
                        {
                            Id = 2,
                            DiscountPercentage = 15m,
                            EndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Summer Shape Discount",
                            StartDate = new DateTime(2026, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubscriptionId = 2
                        });
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraineeSubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TraineeSubscriptionId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1400m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Amount = 800m,
                            Method = "Card",
                            PaidAt = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 4
                        },
                        new
                        {
                            Id = 5,
                            Amount = 1400m,
                            Method = "Cash",
                            PaidAt = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 5
                        },
                        new
                        {
                            Id = 6,
                            Amount = 800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 6
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1400m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 7
                        },
                        new
                        {
                            Id = 8,
                            Amount = 1800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 8
                        },
                        new
                        {
                            Id = 9,
                            Amount = 800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 9
                        },
                        new
                        {
                            Id = 10,
                            Amount = 1400m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 10
                        },
                        new
                        {
                            Id = 11,
                            Amount = 1800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 11
                        },
                        new
                        {
                            Id = 12,
                            Amount = 800m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 12
                        },
                        new
                        {
                            Id = 13,
                            Amount = 1400m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 13
                        },
                        new
                        {
                            Id = 14,
                            Amount = 1800m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 14
                        },
                        new
                        {
                            Id = 15,
                            Amount = 800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 15
                        },
                        new
                        {
                            Id = 16,
                            Amount = 1400m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 16
                        },
                        new
                        {
                            Id = 17,
                            Amount = 1800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 17
                        },
                        new
                        {
                            Id = 18,
                            Amount = 800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 18
                        },
                        new
                        {
                            Id = 19,
                            Amount = 1400m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 19
                        },
                        new
                        {
                            Id = 20,
                            Amount = 1800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 20
                        },
                        new
                        {
                            Id = 21,
                            Amount = 800m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 21
                        },
                        new
                        {
                            Id = 22,
                            Amount = 1400m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 22
                        },
                        new
                        {
                            Id = 23,
                            Amount = 1800m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 23
                        },
                        new
                        {
                            Id = 24,
                            Amount = 800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 24
                        },
                        new
                        {
                            Id = 25,
                            Amount = 1400m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 25
                        },
                        new
                        {
                            Id = 26,
                            Amount = 1800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 26
                        },
                        new
                        {
                            Id = 27,
                            Amount = 800m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 27
                        },
                        new
                        {
                            Id = 28,
                            Amount = 1400m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 28
                        },
                        new
                        {
                            Id = 29,
                            Amount = 1800m,
                            Method = "Card",
                            PaidAt = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 29
                        },
                        new
                        {
                            Id = 30,
                            Amount = 800m,
                            Method = "Cash",
                            PaidAt = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 30
                        });
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.Trainee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("Trainees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 25,
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Omar Hassan",
                            Phone = "01100000001",
                            Status = 1,
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 30,
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ahmed Samy",
                            Phone = "01100000002",
                            Status = 1,
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 22,
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mohamed Adel",
                            Phone = "01100000003",
                            Status = 3,
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 4,
                            Age = 28,
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Youssef Khaled",
                            Phone = "01100000004",
                            Status = 1,
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 5,
                            Age = 35,
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mahmoud Tarek",
                            Phone = "01100000005",
                            Status = 1,
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 6,
                            Age = 27,
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ali Ibrahim",
                            Phone = "01100000006",
                            Status = 1,
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 7,
                            Age = 24,
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hassan Mostafa",
                            Phone = "01100000007",
                            Status = 2,
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 8,
                            Age = 29,
                            CreatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Karim Nabil",
                            Phone = "01100000008",
                            Status = 1,
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 9,
                            Age = 31,
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Amr Salah",
                            Phone = "01100000009",
                            Status = 3,
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 10,
                            Age = 26,
                            CreatedAt = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mostafa Hany",
                            Phone = "01100000010",
                            Status = 1,
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 11,
                            Age = 23,
                            CreatedAt = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sara Ahmed",
                            Phone = "01100000011",
                            Status = 1,
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 12,
                            Age = 27,
                            CreatedAt = new DateTime(2025, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mona Ali",
                            Phone = "01100000012",
                            Status = 1,
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 13,
                            Age = 21,
                            CreatedAt = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nour Ibrahim",
                            Phone = "01100000013",
                            Status = 2,
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 14,
                            Age = 29,
                            CreatedAt = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aya Khaled",
                            Phone = "01100000014",
                            Status = 1,
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 15,
                            Age = 33,
                            CreatedAt = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Huda Mahmoud",
                            Phone = "01100000015",
                            Status = 3,
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 16,
                            Age = 26,
                            CreatedAt = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Yasmin Adel",
                            Phone = "01100000016",
                            Status = 1,
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 17,
                            Age = 24,
                            CreatedAt = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Salma Tarek",
                            Phone = "01100000017",
                            Status = 1,
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 18,
                            Age = 28,
                            CreatedAt = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Laila Hassan",
                            Phone = "01100000018",
                            Status = 2,
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 19,
                            Age = 32,
                            CreatedAt = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rania Mostafa",
                            Phone = "01100000019",
                            Status = 1,
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 20,
                            Age = 25,
                            CreatedAt = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dina Samy",
                            Phone = "01100000020",
                            Status = 1,
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 21,
                            Age = 34,
                            CreatedAt = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Khaled Fathy",
                            Phone = "01100000021",
                            Status = 1,
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 22,
                            Age = 36,
                            CreatedAt = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tamer Nasser",
                            Phone = "01100000022",
                            Status = 3,
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 23,
                            Age = 38,
                            CreatedAt = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Wael Farouk",
                            Phone = "01100000023",
                            Status = 1,
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 24,
                            Age = 40,
                            CreatedAt = new DateTime(2025, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sherif Adel",
                            Phone = "01100000024",
                            Status = 1,
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 25,
                            Age = 42,
                            CreatedAt = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hany Saad",
                            Phone = "01100000025",
                            Status = 2,
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 26,
                            Age = 27,
                            CreatedAt = new DateTime(2025, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ghada Ali",
                            Phone = "01100000026",
                            Status = 1,
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 27,
                            Age = 31,
                            CreatedAt = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Doaa Hassan",
                            Phone = "01100000027",
                            Status = 1,
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 28,
                            Age = 35,
                            CreatedAt = new DateTime(2025, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Eman Khaled",
                            Phone = "01100000028",
                            Status = 3,
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 29,
                            Age = 37,
                            CreatedAt = new DateTime(2025, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sahar Ibrahim",
                            Phone = "01100000029",
                            Status = 1,
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 30,
                            Age = 39,
                            CreatedAt = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Naglaa Mostafa",
                            Phone = "01100000030",
                            Status = 1,
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 31,
                            Age = 28,
                            CreatedAt = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Fady Nabil",
                            Phone = "01100000031",
                            Status = 1,
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 32,
                            Age = 33,
                            CreatedAt = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "George Samir",
                            Phone = "01100000032",
                            Status = 2,
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 33,
                            Age = 29,
                            CreatedAt = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bishoy Adel",
                            Phone = "01100000033",
                            Status = 1,
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 34,
                            Age = 41,
                            CreatedAt = new DateTime(2025, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ramy Naguib",
                            Phone = "01100000034",
                            Status = 1,
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 35,
                            Age = 26,
                            CreatedAt = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mina Atef",
                            Phone = "01100000035",
                            Status = 3,
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 36,
                            Age = 30,
                            CreatedAt = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tony Magdy",
                            Phone = "01100000036",
                            Status = 1,
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 37,
                            Age = 27,
                            CreatedAt = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Mark Hanna",
                            Phone = "01100000037",
                            Status = 1,
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 38,
                            Age = 34,
                            CreatedAt = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peter Sameh",
                            Phone = "01100000038",
                            Status = 2,
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 39,
                            Age = 36,
                            CreatedAt = new DateTime(2025, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Andrew Fawzy",
                            Phone = "01100000039",
                            Status = 1,
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 40,
                            Age = 32,
                            CreatedAt = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Michael Adel",
                            Phone = "01100000040",
                            Status = 1,
                            TrainerId = 5
                        });
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.TraineeAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<int>("TraineeSubscriptionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TraineeSubscriptionId");

                    b.ToTable("TraineeAttendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckIn = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 1
                        },
                        new
                        {
                            Id = 2,
                            CheckIn = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 1
                        },
                        new
                        {
                            Id = 3,
                            CheckIn = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 1
                        },
                        new
                        {
                            Id = 4,
                            CheckIn = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 2
                        },
                        new
                        {
                            Id = 5,
                            CheckIn = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 2
                        },
                        new
                        {
                            Id = 6,
                            CheckIn = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 2
                        },
                        new
                        {
                            Id = 7,
                            CheckIn = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 3
                        },
                        new
                        {
                            Id = 8,
                            CheckIn = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 3
                        },
                        new
                        {
                            Id = 9,
                            CheckIn = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 3
                        },
                        new
                        {
                            Id = 10,
                            CheckIn = new DateTime(2024, 12, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 4
                        },
                        new
                        {
                            Id = 11,
                            CheckIn = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 4
                        },
                        new
                        {
                            Id = 12,
                            CheckIn = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 5
                        },
                        new
                        {
                            Id = 13,
                            CheckIn = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 5
                        },
                        new
                        {
                            Id = 14,
                            CheckIn = new DateTime(2025, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 6
                        },
                        new
                        {
                            Id = 15,
                            CheckIn = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 6
                        },
                        new
                        {
                            Id = 16,
                            CheckIn = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 7
                        },
                        new
                        {
                            Id = 17,
                            CheckIn = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 7
                        },
                        new
                        {
                            Id = 18,
                            CheckIn = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 8
                        },
                        new
                        {
                            Id = 19,
                            CheckIn = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TraineeSubscriptionId = 8
                        });
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.TraineeSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastCheckIn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Months")
                        .HasColumnType("int");

                    b.Property<int>("PackageTotalDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TraineeId")
                        .HasColumnType("int");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("int");

                    b.Property<int>("UsedDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TraineeId");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("TraineeSubscriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 1,
                            PackageTotalDays = 30,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 1,
                            TrainingProgramId = 1,
                            UsedDays = 18
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 2,
                            PackageTotalDays = 60,
                            StartDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 2,
                            TrainingProgramId = 2,
                            UsedDays = 40
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 3,
                            PackageTotalDays = 90,
                            StartDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 3,
                            TrainingProgramId = 3,
                            UsedDays = 60
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            LastCheckIn = new DateTime(2024, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 1,
                            PackageTotalDays = 30,
                            StartDate = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TraineeId = 4,
                            TrainingProgramId = 1,
                            UsedDays = 30
                        },
                        new
                        {
                            Id = 5,
                            EndDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            LastCheckIn = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 2,
                            PackageTotalDays = 60,
                            StartDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 3,
                            TraineeId = 5,
                            TrainingProgramId = 2,
                            UsedDays = 55
                        },
                        new
                        {
                            Id = 6,
                            EndDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 1,
                            PackageTotalDays = 30,
                            StartDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 6,
                            TrainingProgramId = 1,
                            UsedDays = 10
                        },
                        new
                        {
                            Id = 7,
                            EndDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 2,
                            PackageTotalDays = 60,
                            StartDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TraineeId = 7,
                            TrainingProgramId = 2,
                            UsedDays = 20
                        },
                        new
                        {
                            Id = 8,
                            EndDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 3,
                            PackageTotalDays = 90,
                            StartDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 8,
                            TrainingProgramId = 3,
                            UsedDays = 35
                        },
                        new
                        {
                            Id = 9,
                            EndDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 1,
                            PackageTotalDays = 30,
                            StartDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 9,
                            TrainingProgramId = 1,
                            UsedDays = 5
                        },
                        new
                        {
                            Id = 10,
                            EndDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 2,
                            PackageTotalDays = 60,
                            StartDate = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 10,
                            TrainingProgramId = 2,
                            UsedDays = 15
                        },
                        new
                        {
                            Id = 11,
                            EndDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 3,
                            PackageTotalDays = 90,
                            StartDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 11,
                            TrainingProgramId = 3,
                            UsedDays = 25
                        },
                        new
                        {
                            Id = 12,
                            EndDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 1,
                            PackageTotalDays = 30,
                            StartDate = new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 12,
                            TrainingProgramId = 1,
                            UsedDays = 12
                        },
                        new
                        {
                            Id = 13,
                            EndDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 2,
                            PackageTotalDays = 60,
                            StartDate = new DateTime(2025, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 2,
                            TraineeId = 13,
                            TrainingProgramId = 2,
                            UsedDays = 22
                        },
                        new
                        {
                            Id = 14,
                            EndDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 3,
                            PackageTotalDays = 90,
                            StartDate = new DateTime(2025, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 14,
                            TrainingProgramId = 3,
                            UsedDays = 45
                        },
                        new
                        {
                            Id = 15,
                            EndDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 1,
                            PackageTotalDays = 30,
                            StartDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 15,
                            TrainingProgramId = 1,
                            UsedDays = 8
                        },
                        new
                        {
                            Id = 16,
                            EndDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 2,
                            PackageTotalDays = 60,
                            StartDate = new DateTime(2025, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 16,
                            TrainingProgramId = 2,
                            UsedDays = 10
                        },
                        new
                        {
                            Id = 17,
                            EndDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 3,
                            PackageTotalDays = 90,
                            StartDate = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 17,
                            TrainingProgramId = 3,
                            UsedDays = 20
                        },
                        new
                        {
                            Id = 18,
                            EndDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 1,
                            PackageTotalDays = 30,
                            StartDate = new DateTime(2025, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 18,
                            TrainingProgramId = 1,
                            UsedDays = 3
                        },
                        new
                        {
                            Id = 19,
                            EndDate = new DateTime(2025, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 2,
                            PackageTotalDays = 60,
                            StartDate = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 19,
                            TrainingProgramId = 2,
                            UsedDays = 5
                        },
                        new
                        {
                            Id = 20,
                            EndDate = new DateTime(2025, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 3,
                            PackageTotalDays = 90,
                            StartDate = new DateTime(2025, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 20,
                            TrainingProgramId = 3,
                            UsedDays = 12
                        },
                        new
                        {
                            Id = 21,
                            EndDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 1,
                            PackageTotalDays = 30,
                            StartDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 21,
                            TrainingProgramId = 1,
                            UsedDays = 0
                        },
                        new
                        {
                            Id = 22,
                            EndDate = new DateTime(2025, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 2,
                            PackageTotalDays = 60,
                            StartDate = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 22,
                            TrainingProgramId = 2,
                            UsedDays = 0
                        },
                        new
                        {
                            Id = 23,
                            EndDate = new DateTime(2025, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 3,
                            PackageTotalDays = 90,
                            StartDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 23,
                            TrainingProgramId = 3,
                            UsedDays = 0
                        },
                        new
                        {
                            Id = 24,
                            EndDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 1,
                            PackageTotalDays = 30,
                            StartDate = new DateTime(2025, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 24,
                            TrainingProgramId = 1,
                            UsedDays = 0
                        },
                        new
                        {
                            Id = 25,
                            EndDate = new DateTime(2025, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 2,
                            PackageTotalDays = 60,
                            StartDate = new DateTime(2025, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 25,
                            TrainingProgramId = 2,
                            UsedDays = 0
                        },
                        new
                        {
                            Id = 26,
                            EndDate = new DateTime(2025, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 3,
                            PackageTotalDays = 90,
                            StartDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 26,
                            TrainingProgramId = 3,
                            UsedDays = 0
                        },
                        new
                        {
                            Id = 27,
                            EndDate = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 1,
                            PackageTotalDays = 30,
                            StartDate = new DateTime(2025, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 27,
                            TrainingProgramId = 1,
                            UsedDays = 0
                        },
                        new
                        {
                            Id = 28,
                            EndDate = new DateTime(2025, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 2,
                            PackageTotalDays = 60,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 28,
                            TrainingProgramId = 2,
                            UsedDays = 0
                        },
                        new
                        {
                            Id = 29,
                            EndDate = new DateTime(2025, 8, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 3,
                            PackageTotalDays = 90,
                            StartDate = new DateTime(2025, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 29,
                            TrainingProgramId = 3,
                            UsedDays = 0
                        },
                        new
                        {
                            Id = 30,
                            EndDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            LastCheckIn = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Months = 1,
                            PackageTotalDays = 30,
                            StartDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            TraineeId = 30,
                            TrainingProgramId = 1,
                            UsedDays = 0
                        });
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Trainers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HireDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Ahmed Hassan",
                            Phone = "01000000001",
                            Salary = 8000m,
                            Specialty = "Fitness"
                        },
                        new
                        {
                            Id = 2,
                            HireDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Mohamed Ali",
                            Phone = "01000000002",
                            Salary = 9000m,
                            Specialty = "Bodybuilding"
                        },
                        new
                        {
                            Id = 3,
                            HireDate = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Sara Ibrahim",
                            Phone = "01000000003",
                            Salary = 7000m,
                            Specialty = "Yoga"
                        },
                        new
                        {
                            Id = 4,
                            HireDate = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Mona Khaled",
                            Phone = "01000000004",
                            Salary = 6500m,
                            Specialty = "Zumba"
                        },
                        new
                        {
                            Id = 5,
                            HireDate = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Name = "Omar Tarek",
                            Phone = "01000000005",
                            Salary = 9500m,
                            Specialty = "CrossFit"
                        });
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.TrainerAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrainerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainerAttendances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CheckIn = new DateTime(2025, 5, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 1, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Normal shift",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 2,
                            CheckIn = new DateTime(2025, 5, 2, 8, 15, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 2, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Slightly late",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 3,
                            CheckIn = new DateTime(2025, 5, 3, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 3, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Normal shift",
                            TrainerId = 1
                        },
                        new
                        {
                            Id = 4,
                            CheckIn = new DateTime(2025, 5, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 1, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Morning shift",
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 5,
                            CheckIn = new DateTime(2025, 5, 2, 9, 10, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 2, 17, 20, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Normal shift",
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 6,
                            CheckIn = new DateTime(2025, 5, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 3, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Normal shift",
                            TrainerId = 2
                        },
                        new
                        {
                            Id = 7,
                            CheckIn = new DateTime(2025, 5, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 1, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Evening shift",
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 8,
                            CheckIn = new DateTime(2025, 5, 2, 10, 5, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 2, 18, 10, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Normal shift",
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 9,
                            CheckIn = new DateTime(2025, 5, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 3, 17, 50, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Left early",
                            TrainerId = 3
                        },
                        new
                        {
                            Id = 10,
                            CheckIn = new DateTime(2025, 5, 1, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 1, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Normal shift",
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 11,
                            CheckIn = new DateTime(2025, 5, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Normal shift",
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 12,
                            CheckIn = new DateTime(2025, 5, 3, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 3, 16, 20, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Late check-in",
                            TrainerId = 4
                        },
                        new
                        {
                            Id = 13,
                            CheckIn = new DateTime(2025, 5, 1, 7, 45, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 1, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Early shift",
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 14,
                            CheckIn = new DateTime(2025, 5, 2, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 2, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Normal shift",
                            TrainerId = 5
                        },
                        new
                        {
                            Id = 15,
                            CheckIn = new DateTime(2025, 5, 3, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            CheckOut = new DateTime(2025, 5, 3, 16, 10, 0, 0, DateTimeKind.Unspecified),
                            Date = new DateTime(2025, 5, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Normal shift",
                            TrainerId = 5
                        });
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.TrainingProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AllowedDays")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TrainingPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowedDays = 18,
                            Name = "Boxing",
                            Price = 800m
                        },
                        new
                        {
                            Id = 2,
                            AllowedDays = 20,
                            Name = "Karate",
                            Price = 1400m
                        },
                        new
                        {
                            Id = 3,
                            AllowedDays = 25,
                            Name = "Mixed Fitness",
                            Price = 1800m
                        });
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "hashed_password_1",
                            Role = "Admin",
                            Username = "admin1"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "hashed_password_2",
                            Role = "Admin",
                            Username = "admin2"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordHash = "hashed_password_3",
                            Role = "Admin",
                            Username = "admin3"
                        });
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.Offer", b =>
                {
                    b.HasOne("Gym_Management_System.Data.Models.TrainingProgram", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.Payment", b =>
                {
                    b.HasOne("Gym_Management_System.Data.Models.TraineeSubscription", "TraineeSubscription")
                        .WithMany("Payments")
                        .HasForeignKey("TraineeSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TraineeSubscription");
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.Trainee", b =>
                {
                    b.HasOne("Gym_Management_System.Data.Models.Trainer", "Trainer")
                        .WithMany("Trainees")
                        .HasForeignKey("TrainerId");

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.TraineeAttendance", b =>
                {
                    b.HasOne("Gym_Management_System.Data.Models.TraineeSubscription", "TraineeSubscription")
                        .WithMany()
                        .HasForeignKey("TraineeSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TraineeSubscription");
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.TraineeSubscription", b =>
                {
                    b.HasOne("Gym_Management_System.Data.Models.Trainee", "Trainee")
                        .WithMany("TraineeSubscriptions")
                        .HasForeignKey("TraineeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gym_Management_System.Data.Models.TrainingProgram", "TrainingProgram")
                        .WithMany()
                        .HasForeignKey("TrainingProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainee");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.TrainerAttendance", b =>
                {
                    b.HasOne("Gym_Management_System.Data.Models.Trainer", "Trainer")
                        .WithMany()
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trainer");
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.Trainee", b =>
                {
                    b.Navigation("TraineeSubscriptions");
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.TraineeSubscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Gym_Management_System.Data.Models.Trainer", b =>
                {
                    b.Navigation("Trainees");
                });
#pragma warning restore 612, 618
        }
    }
}
